# The Folding@Home project values, you might want to overwrite user and team.
#
# It relies on the docker image by https://github.com/richarvey/FoldingAtHome.
# If you have your own user or team, override the values below. You can also
# enable/disable gpus, smp, etc.
foldingathome:
  image: null
  # image: richarvey/foldingathome:latest
  config:
    gpu: false
    passkey: ''
    power: "full"
    smp: "true"
    team: "38188"
    user: "CERN_Cloud"
  nodeSelector: {}
  priorityClassName: vlow-priority
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: "1048Mi"
    limits:
      cpu: 1
      memory: "2048Mi"

# Horizontal pod auto scaler configuration. The goal is to backfill the
# cluster with folding@home workloads, so we use an hpa resource with a very high
# number of max replicas (max replicas is currently mandatory).
#
# vlow-priority should be set to < -10, so that the cluster auto-scaler does
# not take them into account.
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10000000
  targetCPU: 90

# A set of predefined priorities for your cluster.
# If you can drop if you already manage priorities yourself, otherwise this
# will setup a default one and a very low priority which is used by the
# workloads (enabling preemption).
priority:
  - name: default-priority
    value: 100000
    default: true
  - name: vlow-priority
    value: -100000

